os: linux
dist: bionic

language: c

install:
    - sudo apt-get update
    - sudo make build-dep

script:
    - make test

before_deploy:
    - ./travis_before_deploy || export TRAVIS_TAG=prerelease

deploy:
    provider: releases
    token: "$GITHUB_TOKEN"
    skip_cleanup: true
    release_notes: "Automatic release created by travis-ci integration"
    prerelease: true
    overwrite: true
    file_glob: true
    file:
        - repack.iso
    on:
        all_branches: true
        condition: $TRAVIS_BRANCH != prerelease
