#!/bin/bash
#
#
#

usage() {
    echo
    echo "Usage: $0 -i filename -o filename [fragment ...]"
}

# Some fixed strings that will change one day
# FIXME - extract this information from the image, dont assume it!
ARCH=amd64
VERSION=10

while getopts "hi:o:" opt; do
    case "$opt" in
        i)
            INPUT=$OPTARG
            ;;
        o)
            OUTPUT=$OPTARG
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

if [ -z "$INPUT" ]; then
    echo "Need input filename"
    exit 1
fi

if [ -z "$OUTPUT" ]; then
    echo "Need output filename"
    exit 1
fi

shift $((OPTIND-1))

set -e

TMP=$(mktemp --directory)
for i in $*; do
    [ -e "$i" ] && cat "$i" >>"$TMP"/preseed.cfg
    shift
done

pushd "$TMP"
echo preseed.cfg | cpio -H newc -R 0:0 -o |gzip -9 >preseed.cpio.gz
popd

DIR=$(mktemp --directory)

xorriso -osirrox on -indev "$INPUT" -extract / "$DIR"
chmod -R a+w "$DIR"

# Add our new preseed to the various initrd files
for i in "$DIR"/install.amd/initrd.gz "$DIR"/install.amd/gtk/initrd.gz; do
    cat "$TMP"/preseed.cpio.gz >>"$i"
done

# Fix up checksums
pushd "$DIR"
find -follow -type f ! -name md5sum.txt -print0 | xargs -0 md5sum > md5sum.txt
popd

# TODO
# - theoretically could extract the $DIR/.disk/mkisofs command
xorriso -as mkisofs -r -checksum_algorithm_iso md5,sha1,sha256,sha512 \
    -J -joliet-long -cache-inodes \
    -isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin \
    -b isolinux/isolinux.bin -c isolinux/boot.cat -boot-load-size 4 \
    -boot-info-table -no-emul-boot -eltorito-alt-boot \
    -e boot/grub/efi.img -no-emul-boot \
    -isohybrid-gpt-basdat \
    -V "Debian $VERSION $ARCH auto" \
    -o "$OUTPUT" \
    "$DIR"

rm -rf "$DIR" "$TMP"
