
name: Continuous Deployment

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    deploy:
        name: Builds a repack
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Install Dependencies
              run: |
                  sudo apt-get update
                  sudo make build-dep

            - name: Build the repack
              run: |
                  make test

            - name: Upload to releases
              uses: softprops/action-gh-release@v1
              with:
                  prerelease: true
                  name: prerelease
                  tag_name: prerelease
                  files: |
                      repack.iso
                      repack.txt

